# Usa uma imagem base do Python mais leve para produção
FROM python:3.9-slim

# Define o diretório de trabalho dentro do container como "buscaReqs"
WORKDIR /buscaComissoesSF

# Copia o arquivo de dependências
COPY requirements.txt requirements.txt

# Instala as dependências sem cache para manter a imagem leve
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código para dentro do container
COPY . .

# Define variáveis de ambiente para evitar problemas no Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Expõe a porta usada pelo Cloud Run
EXPOSE 8080

# Comando de inicialização - Certifique-se de que o nome do script está correto
CMD ["python", "buscaComissoesSF5.py"]
