# Generated by ChatGPT on 2025-10-20
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proposition_id", models.CharField(max_length=64, unique=True)),
                ("sigla_tipo", models.CharField(max_length=16)),
                ("numero", models.CharField(max_length=16)),
                ("ano", models.CharField(max_length=8)),
                ("proposicao", models.CharField(max_length=64)),
                ("autor", models.CharField(blank=True, max_length=255)),
                ("ementa", models.TextField(blank=True)),
                ("situacao", models.CharField(blank=True, max_length=255)),
                ("situacao_tramitacao", models.CharField(blank=True, max_length=255)),
                ("orgao_sigla", models.CharField(blank=True, max_length=64)),
                ("inteiro_teor_url", models.URLField(blank=True)),
                ("ficha_tramitacao_url", models.URLField(blank=True)),
                ("data_apresentacao", models.DateField(blank=True, null=True)),
                ("data_ultima_tramitacao", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-data_ultima_tramitacao", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="proposition",
            index=models.Index(fields=["sigla_tipo"], name="comissoes_p_sigla__f478cf_idx"),
        ),
        migrations.AddIndex(
            model_name="proposition",
            index=models.Index(fields=["orgao_sigla"], name="comissoes_p_orgao_s_c6df21_idx"),
        ),
        migrations.AddIndex(
            model_name="proposition",
            index=models.Index(fields=["proposition_id"], name="comissoes_p_proposi_051b29_idx"),
        ),
    ]
