# Generated by Django 5.1.1 on 2026-02-19 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoProposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(db_index=True, max_length=100)),
                ('casa', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PAUTA', 'Adicionada à pauta'), ('VOTACAO', 'Votação'), ('APROVACAO', 'Aprovada'), ('REJEICAO', 'Rejeitada'), ('TRAMITACAO', 'Tramitação'), ('COMISSAO', 'Encaminhada à comissão'), ('ARQUIVO', 'Arquivada'), ('OUTRA', 'Outra')], max_length=20)),
                ('descricao', models.TextField()),
                ('situacao_anterior', models.CharField(blank=True, max_length=300)),
                ('situacao_atual', models.CharField(blank=True, max_length=300)),
                ('data_atualizacao', models.DateTimeField(db_index=True)),
                ('origem', models.CharField(choices=[('buscaReqs', 'Busca de Requerimentos'), ('buscaSei', 'Busca de Processos SEI'), ('buscaMaterias', 'Busca de Matérias'), ('buscaComissoes', 'Busca de Comissões')], max_length=50)),
                ('detectado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_atualizacao'],
                'indexes': [models.Index(fields=['codigo_material', '-data_atualizacao'], name='agenda_atua_codigo__52dd09_idx'), models.Index(fields=['-data_atualizacao'], name='agenda_atua_data_at_8c5e5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoLegislativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_evento', models.CharField(db_index=True, max_length=100, unique=True)),
                ('casa', models.CharField(choices=[('Câmara', 'Câmara dos Deputados'), ('Senado', 'Senado Federal')], db_index=True, max_length=20)),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('VOTACAO', 'Votação'), ('SESSAO', 'Sessão'), ('COMISSAO', 'Comissão'), ('PLENARIO', 'Plenário'), ('OUTRA', 'Outra')], max_length=20)),
                ('local', models.CharField(blank=True, max_length=300)),
                ('comissao', models.CharField(blank=True, max_length=300)),
                ('data_evento', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('url_evento', models.URLField(blank=True, null=True)),
                ('url_transmissao', models.URLField(blank=True, null=True)),
                ('proposicoes_relacionadas', models.JSONField(blank=True, default=list)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['data_evento', 'hora_inicio'],
                'indexes': [models.Index(fields=['casa', 'data_evento'], name='agenda_even_casa_96f6e0_idx'), models.Index(fields=['-data_evento'], name='agenda_even_data_ev_9ad993_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgendaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comissao_camara', 'Comissão Câmara'), ('comissao_senado', 'Comissão Senado'), ('plenario_camara', 'Plenário Câmara'), ('plenario_senado', 'Plenário Senado')], max_length=20)),
                ('nome', models.CharField(max_length=300)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'nome'],
                'unique_together': {('usuario', 'tipo', 'nome')},
            },
        ),
    ]
