# Use uma imagem Python leve
FROM python:3.9-slim

# Defina o diretório de trabalho
WORKDIR /buscaMateriasSenado

# Copie apenas os arquivos necessários
# Se você tiver um requirements.txt com as dependências, copie-o primeiro
COPY requirements.txt .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie os arquivos da aplicação (por exemplo, app.py e o arquivo Excel)
COPY buscaMateriasSenadoECamara11.py .
COPY proposicoes_ids.xlsx .

# Exponha a porta 8080 (usada pelo Cloud Run)
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["python", "buscaMateriasSenadoECamara11.py"]
